### ISSUE TITLE
Cannot read property 'configurations' of undefined.

### ISSUE THREAD

**Issue by vnaeimabadi** [transistorsoft/rn-background-geolocation-demo#125]
![image](https://user-images.githubusercontent.com/14070643/178114324-b585c134-f437-401e-8169-5085d7b8638e.png)

**Comment by REInVent650** [comment]
followed the instructions and experienced the same error

`reinvent650@MacbookPro rn-background-geolocation-demo-master % react-native run-android

error Cannot read properties of undefined (reading 'configurations').
TypeError: Cannot read properties of undefined (reading 'configurations')
    at Object.dependencyConfig (/Users/reinvent650/Downloads/rn-background-geolocation-demo-master/node_modules/@react-native-community/cli-platform-ios/build/config/index.js:102:37)
    at /usr/local/lib/node_modules/react-native/node_modules/@react-native-community/cli-config/build/loadConfig.js:47:61
    at Array.reduce (<anonymous>)
    at getDependencyConfig (/usr/local/lib/node_modules/react-native/node_modules/@react-native-community/cli-config/build/loadConfig.js:44:51)
    at Object.get @react-native-async-storage/async-storage [as @react-native-async-storage/async-storage] (/usr/local/lib/node_modules/react-native/node_modules/@react-native-community/cli-config/build/loadConfig.js:99:18)
    at warnAboutManuallyLinkedLibs (/Users/reinvent650/Downloads/rn-background-geolocation-demo-master/node_modules/@react-native-community/cli-platform-android/build/link/warnAboutManuallyLinkedLibs.js:39:43)
    at displayWarnings (/Users/reinvent650/Downloads/rn-background-geolocation-demo-master/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:82:44)
    at Object.runAndroid [as func] (/Users/reinvent650/Downloads/rn-background-geolocation-demo-master/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:97:3)
    at Command.handleAction (/usr/local/lib/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:142:23)
    at Command.listener [as _actionHandler] (/usr/local/lib/node_modules/react-native/node_modules/commander/lib/command.js:482:17)
info Run CLI with --verbose flag for more details.
reinvent650@MacbookPro rn-background-geolocation-demo-master % react-native run-ios   
error Cannot read properties of undefined (reading 'configurations').
TypeError: Cannot read properties of undefined (reading 'configurations')
    at Object.dependencyConfig (/Users/reinvent650/Downloads/rn-background-geolocation-demo-master/node_modules/@react-native-community/cli-platform-ios/build/config/index.js:102:37)
    at /usr/local/lib/node_modules/react-native/node_modules/@react-native-community/cli-config/build/loadConfig.js:47:61
    at Array.reduce (<anonymous>)
    at getDependencyConfig (/usr/local/lib/node_modules/react-native/node_modules/@react-native-community/cli-config/build/loadConfig.js:44:51)
    at Object.get @react-native-async-storage/async-storage [as @react-native-async-storage/async-storage] (/usr/local/lib/node_modules/react-native/node_modules/@react-native-community/cli-config/build/loadConfig.js:99:18)
    at warnAboutManuallyLinkedLibs (/Users/reinvent650/Downloads/rn-background-geolocation-demo-master/node_modules/@react-native-community/cli-platform-ios/build/link/warnAboutManuallyLinkedLibs.js:39:43)
    at Object.runIOS [as func] (/Users/reinvent650/Downloads/rn-background-geolocation-demo-master/node_modules/@react-native-community/cli-platform-ios/build/commands/runIOS/index.js:104:44)
    at Command.handleAction (/usr/local/lib/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:142:23)
    at Command.listener [as _actionHandler] (/usr/local/lib/node_modules/react-native/node_modules/commander/lib/command.js:482:17)
    at /usr/local/lib/node_modules/react-native/node_modules/commander/lib/command.js:1264:65
info Run CLI with --verbose flag for more details.`

**Comment by christocracy** [comment]
Have you googled this error?  https://stackoverflow.com/questions/73118211/react-native-0-68-2-after-react-native-run-android-error-cannot-read-properties
